# services/backend/Dockerfile.backend
FROM python:3.12-slim

WORKDIR /app

# ERROR - stderr: permission denied while trying to connect
# to the docker API at unix:///var/run/docker.sock
USER root
# create non root user
# ARG USER_ID=1000
# ARG GROUP_ID=1000

# RUN groupadd -g ${GROUP_ID} appuser && \
#     useradd -u ${USER_ID} -g appuser -m appuser


# Install uv + docker-ce-cli to lauch docker cli from backend service container
# daemon already installed in host, only the cli est needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
    lsb-release \
    && pip install --no-cache-dir uv \
    && install -m 0755 -d /etc/apt/keyrings \
    && curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg \
    && chmod a+r /etc/apt/keyrings/docker.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends docker-ce-cli \
    && rm -rf /var/lib/apt/lists/*

# copy dependency files
COPY pyproject.toml uv.lock ./

# install dependencies
RUN uv sync --frozen --no-dev --group backend --group training

# copy source code
COPY common ./common
COPY services ./services

ENV PYTHONPATH=/app

# create runtime folders
RUN mkdir -p data/processed artifacts/models artifacts/metrics artifacts/reports
# &&\
    # chown -R appuser:appuser /app

# Add appuser to docker group for docker socket access
# RUN groupadd -f docker && usermod -aG docker appuser
# docker sock gid
# ARG DOCKER_GID
# RUN groupadd -g ${DOCKER_GID} docker \
#  && usermod -aG docker appuser

# Switch to non-root user
# USER appuser

EXPOSE 8000

# check .venv exists
RUN ls -la /app/.venv/bin/python

CMD ["/app/.venv/bin/python", "-m", "uvicorn", "services.backend.src.main:app", "--host", "0.0.0.0", "--port", "8000"]
