FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir uv
COPY pyproject.toml uv.lock ./

# Install dependencies
RUN uv sync --frozen --no-dev --group frontend

COPY common ./common
COPY services ./services

ENV PYTHONPATH=/app

EXPOSE 8501

CMD ["/app/.venv/bin/python", "-m", "streamlit", "run", "services/frontend/run.py", "--server.address=0.0.0.0", "--server.port=8501"]
